config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'artifacts#index'

  resources :tags do
    member do
      get 'artifacts'
    end

    collection do
      get 'sort/:field' => 'tags#sort'
    end
  end

  resources :artifacts do
    member do
      get 'groups'
    end

    member do
      get 'users'
    end

    member do
      get 'tags'
    end

    collection do
      get 'sort/:field' => 'artifacts#sort'
    end
  end

  resources :groups do
    member do
      get 'artifacts'
    end

    member do
      get 'users'
    end

    collection do
      get 'sort/:field' => 'groups#sort'
    end
  end

  resources :users, only: [:index, :show] do
    member do
      get 'artifacts'
    end

    member do
      get 'groups'
    end

    collection do
      get 'sort/:field' => 'users#sort'
    end
  end

end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Group < ActiveRecord::Base
	validates :name, presence: true
	validates :name, uniqueness: true

    has_and_belongs_to_many :users
    has_many :artifacts, through: :users
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  def artifacts
    @artifacts = Group.find(params[:id]).artifacts
  end

  def users
    @users = Group.find(params[:id]).users
  end

  def sort
    @groups = []
    if (Group.attribute_names.include? (params[:field])) then
      @groups = Group.order(params[:field])
    end
    
    render :index
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        current_user.groups << @group
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :user_ids => [])
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= collection_select :group, :user_ids, User.all, :id, :email, {}, {:multiple => true} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/artifacts.html.erb
<p id="notice"><%= notice %></p>

<h1>Group's Artifacts</h1>

<table class="table">
  <thead>
    <tr>
      <th><%= link_to "Name", "/artifacts/sort/name" %></th>
      <th><%= link_to "Description", "/artifacts/sort/description" %></th>
      <th><%= link_to "Longitude", "/artifacts/sort/longitude" %></th>
      <th><%= link_to "Latitude", "/artifacts/sort/latitude" %></th>
      <th><%= link_to "Filepath", "/artifacts/sort/filepath" %></th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @artifacts.each do |artifact| %>
      <tr>
        <td><button type="button" class="btn btn-default"><%= link_to "#{artifact.name}", artifact %></button></td>
        <td><%= artifact.description %></td>
        <td><%= artifact.longitude %></td>
        <td><%= artifact.latitude %></td>
        <td><%= artifact.filepath %></td>
        <td><button type="button" class="btn btn-default"><%= link_to 'Edit', edit_artifact_path(artifact) %></button></td>
        <td><button type="button" class="btn btn-warning"><%= link_to 'Destroy', artifact, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<button type="button" class="btn btn-default"><%= link_to 'Back', :back %></button>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Groups</h1>

<table class="table">
  <thead>
    <tr>
      <th><%= link_to "Name", "/groups/sort/name" %></th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><button type="button" class="btn btn-default"><%= link_to "#{group.name}", group %></button></td>
        <td><button type="button" class="btn btn-info"><%= link_to 'Edit', edit_group_path(group) %></button></td>
        <td><button type="button" class="btn btn-warning"><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button type="button" class="btn btn-lg btn-primary"><%= link_to 'New Group', new_group_path %></button>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %>

<button type="button" class="btn btn-default"><%= link_to 'Back', :back %></button>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<div class="row small-buffer"></div>

<p>
  <strong>Group's Users:</strong>
</p>

<table class="table">
  <thead>
    <tr>
      <th><%= link_to "Name", "/users/sort/lastname" %></th>
      <th><%= link_to "ID", "/users/sort/id" %></th>
      <th><%= link_to "Last Sign In", "/users/sort/last_sign_in_at" %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  	<% @users = Group.find(params[:id]).users %>
    <% @users.each do |user| %>
      <tr>
        <td><%= "#{user.firstname} #{user.lastname}" %></td>
        <td><%= user.id %></td>
        <td><%= user.last_sign_in_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="row buffer"></div>

<button type="button" class="btn btn-primary"><%= link_to "Group's Artifacts", "/groups/#{@group.id}/artifacts"  %></button>

<div class="btn-group" role="group" aria-label="...">
  <button type="button" class="btn btn-default"><%= link_to 'Edit', edit_group_path(@group) %></button>
  <button type="button" class="btn btn-default"><%= link_to 'Back', groups_path %></button>
</div>

app/views/groups/users.html.erb
<p id="notice"><%= notice %></p>

<h1>Group's Users</h1>

<table class="table">
  <thead>
    <tr>
      <th><%= link_to "Name", "/users/sort/lastname" %></th>
      <th><%= link_to "Email", "/users/sort/email" %></th>
      <th><%= link_to "ID", "/users/sort/id" %></th>
      <th><%= link_to "Last Sign In", "/users/sort/last_sign_in_at" %></th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><button type="button" class="btn btn-default"><%= link_to "#{user.firstname} #{user.lastname}", user %></button></td>
        <td><%= user.email %></td>
        <td><%= user.id %></td>
        <td><%= user.last_sign_in_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>