config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'artifacts#index'

  resources :tags do
    member do
      get 'artifacts'
    end

    collection do
      get 'sort/:field' => 'tags#sort'
    end
  end

  resources :artifacts do
    member do
      get 'groups'
    end

    member do
      get 'users'
    end

    member do
      get 'tags'
    end

    collection do
      get 'sort/:field' => 'artifacts#sort'
    end
  end

  resources :groups do
    member do
      get 'artifacts'
    end

    member do
      get 'users'
    end

    collection do
      get 'sort/:field' => 'groups#sort'
    end
  end

  resources :users, only: [:index, :show] do
    member do
      get 'artifacts'
    end

    member do
      get 'groups'
    end

    collection do
      get 'sort/:field' => 'users#sort'
    end
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  firstname              :string
#  lastname               :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  failed_attempts        :integer          default(0), not null
#  unlock_token           :string
#  locked_at              :datetime
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable

	has_and_belongs_to_many :groups
	has_and_belongs_to_many :artifacts
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  def artifacts
    @artifacts = User.find(params[:id]).artifacts
  end

  def groups
    @groups = User.find(params[:id]).groups
  end

  def sort
    @users = []
    if (User.attribute_names.include? (params[:field])) then
      @users = User.order(params[:field])
    end
    
    render :index
  end

  # # GET /users/new
  # def new
  #   @user = User.new
  # end

  # # GET /users/1/edit
  # def edit
  # end

  # # POST /users
  # # POST /users.json
  # def create
  #   @user = User.new(user_params)

  #   respond_to do |format|
  #     if @user.save
  #       format.html { redirect_to @user, notice: 'User was successfully created.' }
  #       format.json { render :show, status: :created, location: @user }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PATCH/PUT /users/1
  # # PATCH/PUT /users/1.json
  # def update
  #   respond_to do |format|
  #     if @user.update(user_params)
  #       format.html { redirect_to @user, notice: 'User was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @user }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /users/1
  # # DELETE /users/1.json
  # def destroy
  #   @user.destroy
  #   respond_to do |format|
  #     format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # # Never trust parameters from the scary internet, only allow the white list through.
    # def user_params
    #   params.require(:user).permit(:firstname, :lastname)
    # end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/artifacts.html.erb
<p id="notice"><%= notice %></p>

<h1>Your Artifacts</h1>

<table class="table">
  <thead>
    <tr>
      <th><%= link_to "Name", "/artifacts/sort/name" %></th>
      <th><%= link_to "Description", "/artifacts/sort/description" %></th>
      <th><%= link_to "Longitude", "/artifacts/sort/longitude" %></th>
      <th><%= link_to "Latitude", "/artifacts/sort/latitude" %></th>
      <th><%= link_to "Filepath", "/artifacts/sort/filepath" %></th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @artifacts.each do |artifact| %>
      <tr>
        <td><button type="button" class="btn btn-default"><%= link_to "#{artifact.name}", artifact %></button></td>
        <td><%= artifact.description %></td>
        <td><%= artifact.longitude %></td>
        <td><%= artifact.latitude %></td>
        <td><%= artifact.filepath %></td>
        <td><button type="button" class="btn btn-default"><%= link_to 'Edit', edit_artifact_path(artifact) %></button></td>
        <td><button type="button" class="btn btn-warning"><%= link_to 'Destroy', artifact, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button type="button" class="btn btn-lg btn-primary"><%= link_to 'New Artifact', new_artifact_path %></button>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<button type="button" class="btn btn-default"><%= link_to 'Back', :back %></button>

app/views/users/groups.html.erb
<p id="notice"><%= notice %></p>

<h1>Your Groups</h1>

<table class="table">
  <thead>
    <tr>
      <th><%= link_to "Name", "/groups/sort/name" %></th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><button type="button" class="btn btn-default"><%= link_to "#{group.name}", group %></button></td>
        <td><button type="button" class="btn btn-default"><%= link_to 'Edit', edit_group_path(group) %></button></td>
        <td><button type="button" class="btn btn-warning"><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button type="button" class="btn btn-lg btn-primary"><%= link_to 'New Group', new_group_path %></button>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table">
  <thead>
    <tr>
      <th><%= link_to "Name", "/users/sort/lastname" %></th>
      <th><%= link_to "Email", "/users/sort/email" %></th>
      <th><%= link_to "ID", "/users/sort/id" %></th>
      <th><%= link_to "Last Sign In", "/users/sort/last_sign_in_at" %></th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><button type="button" class="btn btn-default"><%= link_to "#{user.firstname} #{user.lastname}", user %></button></td>
        <td><%= user.email %></td>
        <td><%= user.id %></td>
        <td><%= user.last_sign_in_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<button type="button" class="btn btn-default"><%= link_to 'Back', :back %></button>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @user.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>ID:</strong>
  <%= @user.id %>
</p>

<p>
  <strong>Created At:</strong>
  <%= @user.created_at %>
</p>

<button type="button" class="btn btn-default"><%= link_to 'Back', users_path %></button>