config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'artifacts#index'

  resources :tags do
    member do
      get 'artifacts'
    end

    collection do
      get 'sort/:field' => 'tags#sort'
    end
  end

  resources :artifacts do
    member do
      get 'groups'
    end

    member do
      get 'users'
    end

    member do
      get 'tags'
    end

    collection do
      get 'sort/:field' => 'artifacts#sort'
    end
  end

  resources :groups do
    member do
      get 'artifacts'
    end

    member do
      get 'users'
    end

    collection do
      get 'sort/:field' => 'groups#sort'
    end
  end

  resources :users, only: [:index, :show] do
    member do
      get 'artifacts'
    end

    member do
      get 'groups'
    end

    collection do
      get 'sort/:field' => 'users#sort'
    end
  end

end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id          :integer          not null, primary key
#  name        :string
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Tag < ActiveRecord::Base
	validates :name, presence: true
	validates :name, uniqueness: true

	has_and_belongs_to_many :artifacts
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  def artifacts
    @artifacts = Tag.find(params[:id]).artifacts
  end

  def sort
    @tags = []
    if (Tag.attribute_names.include? (params[:field])) then
      @tags = Tag.order(params[:field])
    end

    render :index
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, tag: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, tag: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name, :description)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/artifacts.html.erb
<p id="notice"><%= notice %></p>

<h1>Tag's Artifacts</h1>

<table class="table">
  <thead>
    <tr>
      <th><%= link_to "Name", "/artifacts/sort/name" %></th>
      <th><%= link_to "Description", "/artifacts/sort/description" %></th>
      <th><%= link_to "Longitude", "/artifacts/sort/longitude" %></th>
      <th><%= link_to "Latitude", "/artifacts/sort/latitude" %></th>
      <th><%= link_to "Filepath", "/artifacts/sort/filepath" %></th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @artifacts.each do |artifact| %>
      <tr>
        <td><button type="button" class="btn btn-default"><%= link_to "#{artifact.name}", artifact %></button></td>
        <td><%= artifact.description %></td>
        <td><%= artifact.longitude %></td>
        <td><%= artifact.latitude %></td>
        <td><%= artifact.filepath %></td>
        <td><button type="button" class="btn btn-default"><%= link_to 'Edit', edit_artifact_path(artifact) %></button></td>
        <td><button type="button" class="btn btn-warning"><%= link_to 'Destroy', artifact, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form' %>

<button type="button" class="btn btn-default"><%= link_to 'Back', :back %></button>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tags</h1>

<table class="table">
  <thead>
    <tr>
      <th><%= link_to "Name", "/tags/sort/name" %></th>
      <th><%= link_to "Description", "/tags/sort/description" %></th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><button type="button" class="btn btn-default"><%= link_to "#{tag.name}", tag %></button></td>
        <td><%= tag.description %></td>
        <td><button type="button" class="btn btn-default"><%= link_to 'Edit', edit_tag_path(tag) %></button></td>
        <td><button type="button" class="btn btn-warning"><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button type="button" class="btn btn-lg btn-primary"><%= link_to 'New Tag', new_tag_path %></button>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form' %>

<button type="button" class="btn btn-default"><%= link_to 'Back', :back %></button>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tag.description %>
</p>

<button type="button" class="btn btn-primary"><%= link_to "Tag's Artifacts", "/tags/#{@tag.id}/artifacts"  %></button>

<div class="btn-group" role="group" aria-label="...">
  <button type="button" class="btn btn-default"><%= link_to 'Edit', edit_tag_path(@tag) %></button>
  <button type="button" class="btn btn-default"><%= link_to 'Back', tags_path %></button>
</div>