config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'artifacts#index'

  resources :tags do
    member do
      get 'artifacts'
    end

    collection do
      get 'sort/:field' => 'tags#sort'
    end
  end

  resources :artifacts do
    member do
      get 'groups'
    end

    member do
      get 'users'
    end

    member do
      get 'tags'
    end

    collection do
      get 'sort/:field' => 'artifacts#sort'
    end
  end

  resources :groups do
    member do
      get 'artifacts'
    end

    member do
      get 'users'
    end

    collection do
      get 'sort/:field' => 'groups#sort'
    end
  end

  resources :users, only: [:index, :show] do
    member do
      get 'artifacts'
    end

    member do
      get 'groups'
    end

    collection do
      get 'sort/:field' => 'users#sort'
    end
  end

end

app/models/artifact.rb
# == Schema Information
#
# Table name: artifacts
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  longitude   :float
#  latitude    :float
#  filepath    :text
#

class Artifact < ActiveRecord::Base
	validates :name, presence: true
	validates :name, uniqueness: true

	has_and_belongs_to_many :users
	has_and_belongs_to_many :tags
	has_many :groups, through: :users

	has_attached_file :file #img
	has_attached_file :model #3d model

	# validates_attachment_content_type :file, :content_type => [/\Aimage\/.*\Z/, /\Avideo\/.*\Z/]
	# validates_attachment_content_type :model, :content_type => [/\Aapplication\/.*\Z/, /\Atext\/.*\Z/]
	do_not_validate_attachment_file_type :file
	do_not_validate_attachment_file_type :model


end

app/controllers/artifacts_controller.rb
class ArtifactsController < ApplicationController
  before_action :set_artifact, only: [:show, :edit, :update, :destroy]

  # GET /artifacts
  # GET /artifacts.json
  def index
    @artifacts = Artifact.all
  end

  # GET /artifacts/1
  # GET /artifacts/1.json
  def show
  end

  def groups
    @groups = Artifact.find(params[:id]).groups
  end

  def users
    @users = Artifact.find(params[:id]).users
  end

  def tags
    @tags = Artifact.find(params[:id]).tags
  end

  # def locations
  #   @locations = Artifact.find(params[:id]).locations
  # end

  def sort
    @artifacts = []
    if (Artifact.attribute_names.include? (params[:field])) then
      @artifacts = Artifact.order(params[:field])
    end

    render :index
  end

  # GET /artifacts/new
  def new
    @artifact = Artifact.new
  end

  # GET /artifacts/1/edit
  def edit
  end

  # POST /artifacts
  # POST /artifacts.json
  def create

    @artifact = Artifact.new(artifact_params)

    respond_to do |format|
      if @artifact.save
        current_user.artifacts << @artifact
        format.html { redirect_to @artifact, notice: 'Artifact was successfully created.' }
        format.json { render :show, status: :created, location: @artifact }
      else
        format.html { render :new }
        format.json { render json: @artifact.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /artifacts/1
  # PATCH/PUT /artifacts/1.json
  def update
    respond_to do |format|
      if @artifact.update(artifact_params)
        format.html { redirect_to @artifact, notice: 'Artifact was successfully updated.' }
        format.json { render :show, status: :ok, location: @artifact }
      else
        format.html { render :edit }
        format.json { render json: @artifact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artifacts/1
  # DELETE /artifacts/1.json
  def destroy
    @artifact.destroy
    respond_to do |format|
      format.html { redirect_to artifacts_url, notice: 'Artifact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artifact
      @artifact = Artifact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artifact_params
      params.require(:artifact).permit(:name, :description, :longitude, :latitude, :filepath, :file, :model, :tag_ids => [])
    end

end

app/helpers/artifacts_helper.rb
module ArtifactsHelper
end

app/views/artifacts/_form.html.erb
<%= form_for @artifact, html: { multipart: true } do |f| %>
  <% if @artifact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artifact.errors.count, "error") %> prohibited this artifact from being saved:</h2>

      <ul>
      <% @artifact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :tag_id %><br>
    <%= collection_select :artifact, :tag_ids, Tag.all, :id, :name, {}, {:multiple => true} %>
  </div>
  <div class="field">
    <%= f.label :filepath %><br>
    <%= f.text_field :filepath %>
  </div>
  <div class="field">
    <%= f.label :file %><br>
    <%= f.file_field :file %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.file_field :model %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/artifacts/edit.html.erb
<h1>Editing Artifact</h1>

<%= render 'form' %>

<button type="button" class="btn btn-default"><%= link_to 'Back', :back %></button>

app/views/artifacts/groups.html.erb
<p id="notice"><%= notice %></p>

<h1>Artifact's Groups</h1>

<table class="table">
  <thead>
    <tr>
      <th><%= link_to "Name", "/groups/sort/name" %></th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><button type="button" class="btn btn-default"><%= link_to "#{group.name}", group %></button></td>
        <td><button type="button" class="btn btn-default"><%= link_to 'Edit', edit_group_path(group) %></button></td>
        <td><button type="button" class="btn btn-warning"><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/artifacts/index.html.erb
<p id="notice"><%= notice %></p>

<div>

<h1>Welcome to Artifact Tracker!</h1>
<p>We are the single best place to store, share, and analyze your 3D artifacts! Please upload artifact files above, navigate to the "Tags" page to add extra metadata to your artifacts. You can also join or create groups via the "Groups" page to share your metadata and files with other researchers. You can find more people in the "Users" page.</p>

</div>

<h1>Artifacts</h1>

<table class="table">
  <thead>
    <tr>
      <th><%= link_to "Name", "/artifacts/sort/name" %></th>
      <th><%= link_to "Description", "/artifacts/sort/description" %></th>
      <th><%= link_to "Longitude", "/artifacts/sort/longitude" %></th>
      <th><%= link_to "Latitude", "/artifacts/sort/latitude" %></th>
      <th><%= link_to "Filepath", "/artifacts/sort/filepath" %></th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @artifacts.each do |artifact| %>
      <tr>
        <td><button type="button" class="btn btn-default"><%= link_to "#{artifact.name}", artifact %></button></td>
        <td><%= artifact.description %></td>
        <td><%= artifact.longitude %></td>
        <td><%= artifact.latitude %></td>
        <td><%= artifact.filepath %></td>
        <td><button type="button" class="btn btn-default"><%= link_to 'Edit', edit_artifact_path(artifact) %></button></td>
        <td><button type="button" class="btn btn-warning"><%= link_to 'Destroy', artifact, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button type="button" class="btn btn-lg btn-primary"><%= link_to 'New Artifact', new_artifact_path %></button>

app/views/artifacts/new.html.erb
<h1>New Artifact</h1>

<%= render 'form' %>

<button type="button" class="btn btn-default"><%= link_to 'Back', :back %></button>

app/views/artifacts/show.html.erb
<p id="notice"><%= notice %></p>

</br>
<p>
  <strong>Name:</strong>
  <%= @artifact.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @artifact.description %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @artifact.longitude %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @artifact.latitude %>
</p>

<p>
  <strong>Filepath:</strong>
  <%= @artifact.filepath %>
</p>

<div class="row small-buffer"></div>

<p>
  <strong>Artifact's Tags:</strong>
</p>

<table class="table">
  <thead>
    <tr>
      <th><%= link_to "Name", "/tags/sort/name" %></th>
      <th><%= link_to "Description", "/tags/sort/description" %></th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags = Artifact.find(params[:id]).tags %>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= tag.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="row buffer"></div>

<% if @artifact.file?%>
  <p>
    <strong>Media:</strong>
  </p>
  </br>
  <div><%= image_tag @artifact.file.url %></div>
  </br>
<% end %>

<% if @artifact.model?%>
  <script type="text/javascript">
      var path = '<%=escape_javascript @artifact.model.url %>'
      vtkRender(path);
  </script>
<% end %>

<button type="button" class="btn btn-primary"><%= link_to "Artifact's Users", "/artifacts/#{@artifact.id}/users"  %></button>

<button type="button" class="btn btn-primary"><%= link_to "Artifact's Groups", "/artifacts/#{@artifact.id}/groups"  %></button>

<div class="btn-group" role="group" aria-label="...">
  <button type="button" class="btn btn-default"><%= link_to 'Edit', edit_artifact_path(@artifact) %></button>
  <button type="button" class="btn btn-default"><%= link_to 'Back', artifacts_path %></button>
</div>

app/views/artifacts/tags.html.erb
<p id="notice"><%= notice %></p>

<h1>Artifact's Tags</h1>

<table class="table">
  <thead>
    <tr>
      <th><%= link_to "Name", "/tags/sort/name" %></th>
      <th><%= link_to "Description", "/tags/sort/description" %></th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><button type="button" class="btn btn-default"><%= link_to "#{tag.name}", tag %></button></td>
        <td><%= tag.description %></td>
        <td><button type="button" class="btn btn-default"><%= link_to 'Edit', edit_tag_path(tag) %></button></td>
        <td><button type="button" class="btn btn-warning"><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/artifacts/users.html.erb
<p id="notice"><%= notice %></p>

<h1>Artifact's Users</h1>

<table class="table">
  <thead>
    <tr>
      <th><%= link_to "Name", "/users/sort/lastname" %></th>
      <th><%= link_to "Email", "/users/sort/email" %></th>
      <th><%= link_to "ID", "/users/sort/id" %></th>
      <th><%= link_to "Last Sign In", "/users/sort/last_sign_in_at" %></th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><button type="button" class="btn btn-default"><%= link_to "#{user.firstname} #{user.lastname}", user %></button></td>
        <td><%= user.email %></td>
        <td><%= user.id %></td>
        <td><%= user.last_sign_in_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>